# Generated by Django 4.1.2 on 2022-10-25 12:57

import agri_trade.marketplace.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Cereals', 'Cereals'), ('Pulses', 'Pulses'), ('Nuts', 'Nuts'), ('Oilseeds', 'Oilseeds'), ('Sugar and starch', 'Sugar and starch'), ('Fiber Crops', 'Fiber Crops'), ('Beverages', 'Beverages'), ('Narcotics', 'Narcotics'), ('Spices', 'Spices'), ('Forages', 'Forages'), ('Vegetables', 'Vegetables'), ('Fruits', 'Fruits')], max_length=16)),
                ('variety', models.CharField(blank=True, max_length=25, null=True)),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('form', models.CharField(blank=True, max_length=25, null=True)),
                ('size', models.CharField(blank=True, max_length=25, null=True)),
                ('cultivation_type', models.CharField(choices=[('Organic', 'Organic'), ('Conventional', 'Conventional'), ('In Conversion', 'In Conversion')], max_length=13)),
                ('available_volume', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produces', validators=[agri_trade.marketplace.validators.file_size])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
