# Generated by Django 4.1.2 on 2022-10-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_created_on_product_edited_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
