# Generated by Django 4.1.2 on 2022-11-22 12:48

import agri_trade.marketplace.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[agri_trade.marketplace.validators.file_size]),
        ),
    ]
