# Generated by Django 4.1.2 on 2022-10-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='vat',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
