# Generated by Django 4.1.2 on 2022-11-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_product_location_alter_product_origin'),
        ('accounts', '0005_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='favourites',
            field=models.ManyToManyField(blank=True, null=True, to='marketplace.product'),
        ),
    ]
