# Generated by Django 4.1.2 on 2022-11-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0004_alter_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
