# Generated by Django 4.1.2 on 2022-11-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='posts'),
            preserve_default=False,
        ),
    ]
