# Generated by Django 4.1.2 on 2022-11-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subtopic',
            new_name='subtitle',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Markets', 'Markets'), ('Technology', 'Technology'), ('Others', 'Others')], max_length=11),
        ),
    ]
