# Generated by Django 4.1.2 on 2022-11-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_subtopic_post_subtitle_post_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
